[theme]
primaryColor = "#6667AB"          # lavender / Very Peri
backgroundColor = "#0E0E0E"       # almost-black neutral background
secondaryBackgroundColor = "#1F1F1F" # dark grey for containers & sidebar
textColor = "#FFFFFF"              # white text for high contrast
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = true
enableStaticServing = true
maxUploadSize = 200
maxMessageSize = 200

[global]
developmentMode = false
showWarningOnDirectExecution = false

[client]
caching = true
displayEnabled = true

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s" 